### PR TITLE
[DROOLS-7289] Implement accumulate

### PR DESCRIPTION
**Pull request by tkobayas**
https://issues.redhat.com/browse/DROOLS-7289

### CODE REVIEW

**Review by gitgabrio — COMMENTED** [review]
THanks @tkobayas 
I really can't evaluate this PR, TBH. My only question, out of curiosity, is if there is a real conceptual difference between "Expression" and "Accumulate": it is not "Accumulate" a kind of "Expression" ?

I'm asking because of that change:

`patternSource : fromExpression
              | fromAccumulate
              ;`

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
Hi @gitgabrio  

> there is a real conceptual difference between "Expression" and "Accumulate": is it not "Accumulate" a kind of "Expression" ?

"Expression" is a usual java expression including a bind variable reference (e.g. `$list`) and a method invocation (e.g. `$string.length()`).

`accumulate` is a specific syntax, so requires a specific parser rule.

Thanks!

**Review by gitgabrio — APPROVED** [review]
Thanks @tkobayas LGTM!

**Comment by gitgabrio** [comment]
> Hi @gitgabrio
> 
> > there is a real conceptual difference between "Expression" and "Accumulate": is it not "Accumulate" a kind of "Expression" ?
> 
> "Expression" is a usual java expression including a bind variable reference (e.g. `$list`) and a method invocation (e.g. `$string.length()`).
> 
> `accumulate` is a specific syntax, so requires a specific parser rule.
> 
> Thanks!

Thanks for eplenation, @tkobayas !

**Pull request merged**
